services:
  - type: web
    name: laqueva-laravel
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PHP_VERSION
        value: "8.2"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STDERR_FORMATTER
        value: Monolog\Formatter\JsonFormatter
    # Descomentar y configurar si usas base de datos
    # - key: DATABASE_URL
    #   value: your_database_url_here
    # - key: APP_KEY
    #   value: your_app_key_here
