services:
  - type: web
    name: laqueva-laravel
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:bm32SsL5Fqi9rkMHrgniBygvZa8eEBnYU5NlGtcxVxU=
      - key: APP_URL
        value: https://laquevapizza.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: ASSET_URL
        value: https://laquevapizza.onrender.com
      - key: MIX_ASSET_URL
        value: https://laquevapizza.onrender.com
      - key: VITE_APP_NAME
        value: "La Queva Pizzería"
      - key: APP_FORCE_HTTPS
        value: "true"
      # Configuración PostgreSQL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1nue22dbo4c73f346eg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgre_laqueva
      - key: DB_USERNAME
        value: postgre_laqueva_user
      - key: DB_PASSWORD
        value: 76dEXldIGg8FCCMDX6iJxR6mtsdLOOe6
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
